### ISSUE TITLE
Update FFmageLoading

### ISSUE THREAD

**Issue by wcoder** [Softeq/XToolkit.WhiteLabel#119]
Current: 2.4.4.859
Latest: 2.4.11.982
Diff: https://github.com/luberda-molinet/FFImageLoading/compare/v2.4.4...v2.4.11

Releases: https://github.com/luberda-molinet/FFImageLoading/releases

### Affected
- Droid `LoadImageWithTextPlaceholder` extension method:  https://github.com/Softeq/XToolkit.WhiteLabel/blob/cd38fe374730e8cc7cb4603a22b61102985216f3/Softeq.XToolkit.WhiteLabel.Droid/Extensions/ImageViewExtensions.cs#L14
**After implicit update to the latest FF package, the target app will crash.**
- Droid `FullScreenImageDialogFragment` linker error:
https://github.com/Softeq/XToolkit.WhiteLabel/blob/0ab770495422fcbd5872cbd094406db6c927d386/Softeq.XToolkit.WhiteLabel.Droid/Views/FullScreenImageDialogFragment.cs#L59
> Mono.Linker.MarkException: Error processing method: 'System.Void Softeq.XToolkit.WhiteLabel.Droid.Views.FullScreenImageDialogFragment::OnViewCreated(Android.Views.View,Android.OS.Bundle)' in assembly: 'Softeq.XToolkit.WhiteLabel.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task`1<FFImageLoading.Work.IScheduledWork> FFImageLoading.TaskParameterPlatformExtensions::IntoAsync(FFImageLoading.Work.TaskParameter,FFImageLoading.Views.ImageViewAsync)

**Comment by fryette** [comment]
ios version  2.4.3 need to update too
