### ISSUE TITLE
Dialog service not always show dialog on top

### ISSUE THREAD

**Issue by fryette** [Softeq/XToolkit.WhiteLabel#120]
Current result:
Dialog service show dialog not on the top

Expected Result:
Dialog service should always show dialog over all `Views` and `Windows`

Steps to reproduce:

```
var window = UIApplication.SharedApplication.Windows.FirstOrDefault(x => x.WindowLevel == UIWindowLevel.Normal);
window.AddSubview(new UIView(BackgroundColor.Red));
_dialogService.ShowDialog();
```

**Comment by wcoder** [comment]
Pushed temporary solution.

Could you please check [feature/ios-top-alert-dialog](https://github.com/Softeq/XToolkit.WhiteLabel/tree/feature/ios-top-alert-dialog) branch?
