### ISSUE TITLE
Messenger, Unregister flow

### ISSUE THREAD

**Issue by fryette** [Softeq/XToolkit.WhiteLabel#122]
To remove the action from Messenger you need to call

`Messenger.Default.Unregister<YourClass>(this, HandleMessege);`

I'm not sure, but why we need `HandleMessege` for unregistering?
It would be much clear if we remove action for `Unregister` method

To unregister everything we need is:
1) Message type
2) object

We no need to pass action for unregistering process

**Comment by wcoder** [comment]
Messenger provides some methods for unregister.

You can choose a better method for your case.

In simple case you can use:
```cs
Messenger.Default.Unregister<MessageType>(this);
```
Description:
https://github.com/Softeq/XToolkit.WhiteLabel/blob/e6c40aefa24d5df24cb4fc04dbc5847bcbdddaec/Softeq.XToolkit.WhiteLabel/Messenger/IMessenger.cs#L200-L215

In other advanced cases, when you have more than one subscription for the same message type, you can use another approach for unregistering, via token or concrete method.

```cs
Messenger.Default.Unregister<MessageType>(this, token);

Messenger.Default.Unregister<MessageType>(this, token, MessageHandler);
```
