### ISSUE TITLE
OS Version Support Documentation

### ISSUE THREAD

**Issue by AlexandraMash** [Softeq/XToolkit.WhiteLabel#207]
It would be very helpful to have documented minimal versions of OSs that the whole library and separate projects support (like iOS 11+, Android 21+ for instance). We might also want to mention the latest versions with which the projects are properly working for sure.
We can do it here in Wiki: all gathered on a separate page + on each page that describes some of the features/components.

**Comment by wcoder** [comment]
Added to the Wiki:

https://github.com/Softeq/XToolkit.WhiteLabel/wiki/Version-Support
