### ISSUE TITLE
Execute.OnUIThread() might cause deadlock

### ISSUE THREAD

**Issue by TimofeyBurak** [Softeq/XToolkit.WhiteLabel#259]
### Description

iOS implementation of Execute.OnUIThread() is using Task.Wait(), which is not really safe as it might cause dead-locks

### Steps to Reproduce

https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#async-all-the-way

### Expected Behavior

It is safe to use OnUIThread() anywhere

### Actual Behavior

You should be cautious not to cause deadlocks

### Basic Information

- Version with issue: doesn't seem like we tracking versions, really.. latest master
- Last known good version: none
- IDE: JetBrains Rider 2019.3.3
- Platform Target Frameworks:
  - iOS:  11.0

**Comment by wcoder** [comment]
This behavior was ported from Caliburn.Micro 🙁 

Also, Android part has the same issue:
https://github.com/Softeq/XToolkit.WhiteLabel/blob/6d674e9ba1aeb9092340cf703c927e67ba792178/Softeq.XToolkit.WhiteLabel.Droid/Providers/DroidPlatformProvider.cs#L73

**Comment by wcoder** [comment]
Finally, `OnUIThread` always will be locked in the main thread because any CPU-sensitive operation ran synchronously will lock a thread.

The only in this case, replacing `.Wait()` will be a stylistic solution.

**Comment by TimofeyBurak** [comment]
@wcoder Well, yes, `OnUIThread` is synchronous operation, and programmer should always consider it when choosing between `OnUIThread/OnUIThreadAsync/BeginOnUIThread`. 

But if we expose all of this methods - they all need to be safe to use. Being forced to wait until `OnUIThread` completes synchronously is one thing, it is acceptable and expected behavior for this kind of method, but being forced to wait indefinitely because of the deadlock - that is an issue.

Regarding the implementation - it's just strange that synchronous method is using asynchronous implementation, but not vice versa.

And one more small note, regarding usage of the 'BeginOnUIThread' - we used to populate usage of this method instead of `OnUIThread` in the project, but recently @Synthezator find out that it is actually not very convenient, as we cannot track exceptions inside 'BeginOnUIThread' unless we additionally cover the whole lambda with try-catch block

**Comment by wcoder** [comment]
Related PR: #273

**Comment by wcoder** [comment]
Linked Xamarin.Forms implementation: https://github.com/Softeq/XToolkit.WhiteLabel/pull/258#discussion_r402653189
