### ISSUE TITLE
Android: crash after backgrounding/foregrounding if DialogFragment is opened

### ISSUE THREAD

**Issue by TimofeyBurak** [Softeq/XToolkit.WhiteLabel#340]
### Description

There's no mechanism of restoring ViewModel for DialogFragmentBase<ViewModel>.

### Steps to Reproduce

1. Open DialogFragmentBase<TViewModel> (using DroidFragmentDialogService, for instance)
2. Background the app
3. Trigger fragment recreation (for instance, by changing display settings, like font size)
4. Foreground the app

### Expected Behavior

The same Dialog is opened in the same state

### Actual Behavior

NullReferenceException, because newly created DialogFragment does not have a reference to view model

### Basic Information

- Version with issue: commit 8a940922b1ce861c3a141788772bd7156b6a6039
- Last known good version: none
- IDE: Rider 2020.2
- Platform Target Frameworks:
  - Android: 10

**Comment by vadimpylsky** [comment]
resolved
