### ISSUE TITLE
OnInitialize is not called in Android ViewModels

### ISSUE THREAD

**Issue by Synthezator** [Softeq/XToolkit.WhiteLabel#75]
ViewModelBase has virtual OnInitialize method. 
ActivityBase calls it in OnCreate (ActivityBase.cs:115). But the only code that will be called is "IsInitialized = true" from OnInitialize in ViewModelBase itself, no overridden code from derived viewmodels will be called.

**Comment by wcoder** [comment]
Thanks for the feedback. Currently not relevant.
If will be issues related to this, please open this issue.
